name: Continuous Integration

on:
  pull_request: ~
  push:
    branches: ['main', '*.*.x']

jobs:
  composer-validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.5]
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - run: composer validate --strict --ansi

  check-require:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.2, 8.3, 8.4, 8.5]
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
      - run: composer check-require

  check-unused:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.5]
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
      - run: composer check-unused

  composer-normalize:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.5]
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
      - run: composer normalize --dry-run --diff --ansi

  php-cs-fixer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.5]
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, cs2pr
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
      - run: composer fixcs -- --dry-run --diff --format=checkstyle --ansi | cs2pr

  rector:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.5]
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
      - run: composer rector -- --dry-run

  psalm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.2, 8.3, 8.4, 8.5]
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
      - run: composer psalm -- --php-version=${{ matrix.php }} --stats --output-format=github --shepherd
